.TH ESOLVER 1 "January 2016"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
esolver \- exact mixed integer linear solver
.SH SYNOPSIS
.B esolver
.RI [ options ] " problem_file"
.SH OPTIONS
For a complete summary of options, see the help menu.
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
